server:
  port: 0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: notification-service

  zipkin:
    base-url: http://localhost:9441
  sleuth:
    sampler:
      probability: 1.0