server:
  port: 0


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 190407011
    url: jdbc:mysql://localhost:3306/product_database
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  application:
    name: product-service

management:
  tracing:
    sampling:
      probability: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost